# Site
name: InsideFull
description: This is my web box of personal projects, thoughts and ideas I find interesting
meta_description: Blog filled with Computer Science, AI, self improvement, life logging, and CS projects.
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'stroncea.nicolae@gmail.com'
google_analytics: UA-180310035-1
# google_analytics: UA-103662447-9
disqus: insidefull-com
sharethis:

# Authors
authors:
  john:
    name: Nick
    display_name: InsideFull
    image: /assets/images/nick.jpg
    email: stroncea.nicolae@gmail.com
    web: nicolae-stroncea.github.io
    twitter:
    description:

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
# twitter:
#   username: john
#   card: summary

# facebook:
#   app_id:
#   publisher: john.com
#   admins:

social:
  name: Nick Stroncea
  links:
      # - https://twitter.com/
      # - https://www.facebook.com/
      - https://www.linkedin.com/in/nicolae-stroncea
      - https://github.com/in/nicolae-stroncea
