# Site
name: InsideFull
description: A digital box of thoughts and ideas about life
meta_description: A digital box of thoughts and ideas about life
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
# email: 'stroncea.nicolae@gmail.com'
google_analytics: UA-180310035-1
sharethis:


# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

kramdown:
  parse_block_html: true
  math_engine: mathjax

include:
 - _pages

# SEO
# twitter:
#   username: john
#   card: summary

# facebook:
#   app_id:
#   publisher: john.com
#   admins:
